### ISSUE TITLE
can't launch protonvpn-gui in gentoo systemd: what am i missing?

### ISSUE THREAD

**Issue by lsg333** [Qeenon/mawa#12]
I've succesfully installed protonvpn-gui on gentoo systemd, but can't launch the graphical interface. 
When trying to launch it from terminal as root, i get:
`protonvpn
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-gui==1.10.0', 'console_scripts', 'protonvpn')())
  File "/usr/lib/python-exec/python3.10/protonvpn", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/protonvpn_gui/main.py", line 23, in <module>
    from .view.dashboard import DashboardView
  File "/usr/lib/python3.10/site-packages/protonvpn_gui/view/dashboard.py", line 30, in <module>
    from .dialog import DisplayMessageDialog, TroubleshootDialog
  File "/usr/lib/python3.10/site-packages/protonvpn_gui/view/dialog.py", line 6, in <module>
    gi.require_version("WebKit2", "4.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available
`
Thanks for any tip and sorry if it's a noob question

**Comment by lsg333** [comment]
am i missing something? in Archlinux i just installed it and launched without making any other step.

**Comment by Miezhiko** [comment]
maybe it wants `webkit-gtk`

**Comment by lsg333** [comment]
thanks, it needed that and also` dbus-python`

**Comment by Miezhiko** [comment]
thank you for letting me know, I will add those to deps when I will have time
