### ISSUE TITLE
net-vpn/protonvpn-gui requires net-libs/webkit-gtk:4

### ISSUE THREAD

**Issue by lourdas** [Qeenon/mawa#14]
It seems that the protonvpn-gui client requires the webkit-gtk version from the 4 slot in Gentoo:

    $ protonvpn
    Traceback (most recent call last):
    File "/usr/lib/python-exec/python3.10/protonvpn", line 33, in <module>
        sys.exit(load_entry_point('protonvpn-gui==1.12.0', 'console_scripts', 'protonvpn')())
    File "/usr/lib/python-exec/python3.10/protonvpn", line 25, in importlib_load_entry_point
        return next(matches).load()
    File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
        module = import_module(match.group('module'))
    File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 883, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/usr/lib/python3.10/site-packages/protonvpn_gui/main.py", line 23, in <module>
        from .view.dashboard import DashboardView
    File "/usr/lib/python3.10/site-packages/protonvpn_gui/view/dashboard.py", line 30, in <module>
        from .dialog import DisplayMessageDialog, TroubleshootDialog
    File "/usr/lib/python3.10/site-packages/protonvpn_gui/view/dialog.py", line 6, in <module>
        gi.require_version("WebKit2", "4.0")
    File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
        raise ValueError('Namespace %s not available for version %s' %
    ValueError: Namespace WebKit2 not available for version 4.0

This was with net-libs/webkit-gtk-2.38.3-r500 from the 5 slot. Emerging net-libs/webkit-gtk from the 4 slot (version 2.38.3) fixes the issue.

So, I guess the ebuild should be modified to something like this:

    RDEPEND="
            x11-libs/gtk+:3
            net-libs/webkit-gtk:4
            dev-python/dbus-python[${PYTHON_USEDEP}]
            dev-python/pygobject[${PYTHON_USEDEP}]
            dev-python/psutil[${PYTHON_USEDEP}]
            dev-python/pycairo[${PYTHON_USEDEP}]
            dev-python/jaraco-classes[${PYTHON_USEDEP}]
            appindicator? ( dev-libs/libappindicator:3 )
            >=net-vpn/protonvpn-nm-lib-3.14.0[${PYTHON_USEDEP}]
    "

**Comment by Miezhiko** [comment]
@lourdas yes, guess will do this, alternatively I think it's not hard to patch python code to support version you may want, I don't use this app for a moment.
